---
sample_rate: 44100
segment_seconds: 3.0
train:
    source_types:
        piano:
            maestro:
                hdf5s_directory: "hdf5s/maestro/sr=44100,chn=2/train"
                key_in_hdf5: "piano"
                hop_seconds: 3.0
        symphony:
            instruments_solo:
                hdf5s_directory: "hdf5s/instruments_dataset/symphony_solo/sr=44100,chn=2/train"
                key_in_hdf5: "symphony"
                hop_seconds: 0.1
    indexes: "indexes/piano-symphony/train/sr=44100,piano-symphony.pkl"
