---
sample_rate: 44100
segment_seconds: 3.0
train:
    source_types:
        violin:
            instruments_solo:
                hdf5s_directory: "hdf5s/instruments_solo/violin/sr=44100_chn=2/train"
                key_in_hdf5: "violin"
                hop_seconds: 0.1
        piano:
            maestro:
                hdf5s_directory: "hdf5s/maestro/sr=44100_chn=2/train"
                key_in_hdf5: "piano"
                hop_seconds: 3.0
    indexes: "indexes/violin-piano/sr=44100_chn=2/train/violin-piano.pkl"
