---
sample_rate: 44100
segment_seconds: 3.0
train:
    source_types:
        speech:
            voicebank-demand:
                hdf5s_directory: "hdf5s/voicebank-demand/sr=44100_chn=1/train"
                key_in_hdf5: "speech"
                hop_seconds: 3.
        noise:
            voicebank-demand:
                hdf5s_directory: "hdf5s/voicebank-demand/sr=44100_chn=1/train"
                key_in_hdf5: "noise"
                hop_seconds: 3.
    indexes: "indexes/voicebank-demand/sr=44100_chn=1/train/speech-noise.pkl"
