---
task_name: ambisonic-binaural
train:
    input_source_types:
        - ambisonic
    target_source_types: 
        - binaural
    paired_input_target_data: True
    indexes_dict_path: "indexes/ambisonic-binaural/train/sr=48000.pkl"
    sample_rate: 48000
    input_channels: 4
    output_channels: 2
    segment_seconds: 3.0
    batch_data_preprocessor: AmbisonicBinaural
    model_type: AmbisonicToBinaural_UNetSubbandtimePhase
    loss_type: l1_wav
    optimizer_type: Adam
    mini_data: False
    augmentations:
        remixing_sources: False
        mixaudio:
            ambisonic: 1
    evaluation_callback: default
    learning_rate: 1e-3
    batch_size: 16
    precision: 32
    steps_per_epoch: 10000  # Every 10000 steps is called an `epoch`.
    evaluate_step_frequency: 2000     # Evaluate every #evaluate_step_frequency steps.
    save_step_frequency: 2000  # Save every #save_step_frequency steps.
    early_stop_steps: 10001
    warm_up_steps: 1000
    reduce_lr_steps: 15000
    random_seed: 1234
    resume_checkpoint_path: ""

evaluate:
    batch_size: 1
    segment_seconds: 30.0