---
sample_rate: 44100
segment_seconds: 3.0
train:
    source_types:
        speech:
            vctk:
                hdf5s_directory: "hdf5s/vctk/sr=44100,chn=1/train"
                key_in_hdf5: "speech"
                hop_seconds: 0.1
            musdb18:
                hdf5s_directory: "hdf5s/musdb18/sr=44100,chn=2/train"
                key_in_hdf5: "vocals"
                hop_seconds: 0.1
        accompaniment:
            musdb18:
                hdf5s_directory: "hdf5s/musdb18/sr=44100,chn=2/train"
                key_in_hdf5: "accompaniment"
                hop_seconds: 0.1
    indexes: "indexes/vctk-musdb18/train/sr=44100,speech_vocals-accompaniment.pkl"
